version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    ports:
      - '3000:3000'

  cypress:
    image: cypress/included:12.3.0
    depends_on:
      - app
    environment:
      - CYPRESS_BASE_URL=http://app:3000
    volumes:
      - ./:/e2e
      - /e2e/node_modules
    working_dir: /e2e
    command: sh -c "npm install typescript ts-node && npx cypress run"
